<?php
if (!defined('BARABEAT_MANUAL_RENDER')) { http_response_code(404); exit; }
?>      <section id="interface">
        <h2>2. Interface</h2><p>O aplicativo é composto pela partitura, uma paleta móvel, o menu principal e visualizações opcionais para o modo de prática e o Arranjo.</p>
        <h3>Menu principal</h3><table><thead><tr><th>Menu</th><th>Finalidade</th></tr></thead><tbody><tr><td><strong>Arquivo</strong></td><td>Abrir e salvar partituras, gerenciá-las localmente ou no servidor, exportar e selecionar o idioma. Em smartphones, o manual também fica aqui.</td></tr><tr><td><strong>Partitura</strong></td><td>Criar uma partitura binária, ternária ou em 9/8 e adicionar ou excluir páginas.</td></tr><tr><td><strong>Inserir</strong></td><td>Inserir elementos ou modelos adicionais.</td></tr><tr><td><strong>Ferramentas</strong></td><td>No desktop, abrir modo de prática, Arranjo, manual e seleção de modelos.</td></tr></tbody></table>
        <h3>Idioma</h3><p>Em <strong>Arquivo → Idioma</strong>, escolha <strong>Deutsch</strong>, <strong>English</strong>, <strong>Français</strong>, <strong>Español</strong> ou <strong>Português</strong>. BaraBeat Studio memoriza a escolha. Apenas controles e mensagens mudam; dados musicais, textos livres e partituras salvas não são traduzidos nem alterados.</p>
        <h3>Login</h3><p>Se a proteção estiver ativa, BaraBeat Studio solicita uma senha. O login permanece nesse navegador ou app da Tela de Início até <strong>Arquivo → Sair</strong> ou até apagar os dados. Saia ao usar um dispositivo compartilhado.</p>
        <h3>Administração: acesso temporário</h3><p>Após um login normal, <strong>Arquivo → Abrir acesso por 5 min</strong> suspende temporariamente a senha para todos, inclusive navegadores automatizados, APIs e ferramentas de teste sem login ou cookie. Uma confirmação evita a abertura acidental. O botão mostra o tempo restante e pode fechar antes; a proteção retorna após cinco minutos.</p><p>Nesse período, as respostas recebem <code>noindex</code> e <code>no-store</code>. Ferramentas automatizadas podem acessar, mas mecanismos de busca não devem indexar nem armazenar o aplicativo.</p>
        <h3>Modelos</h3><p><strong>Ferramentas → Modelo</strong> alterna estilos como <strong>Claro</strong>, <strong>Lúdico</strong> e <strong>Terra</strong>. Eles mudam apenas a aparência, nunca os dados musicais.</p>
      </section>
