<?php
if (!defined('BARABEAT_MANUAL_RENDER')) { http_response_code(404); exit; }
?>      <section id="files">
        <h2>3. Abrir e salvar arquivos</h2><p>As partituras são salvas como arquivos <code>.bbs</code>. Partituras antigas <code>.txt</code> continuam compatíveis.</p>
        <h3>Abrir</h3><ul><li><strong>Local</strong> mostra partituras salvas neste navegador ou app da Tela de Início. Elas podem ser organizadas em pastas e subpastas.</li><li><strong>Servidor</strong> mostra partituras de <code>Noten/</code>. A lista é atualizada sempre que o diálogo abre.</li><li>Ao carregar do servidor, BaraBeat Studio memoriza a data e a versão. Se depois houver mudança no servidor, aparece <strong>O servidor foi alterado desde então</strong>. Uma edição local aparece separadamente como <strong>Alterado localmente</strong>, com a data.</li><li>Quando necessário, o aviso oferece <strong>Carregar versão do servidor</strong>.</li><li>Em smartphones, a visualização simplificada mantém acessíveis a abertura e exclusão dos arquivos locais.</li></ul>
        <h3>Salvar</h3><ul><li><strong>Salvar</strong> substitui a partitura aberta.</li><li><strong>Salvar como</strong> cria outro nome ou cópia.</li><li><strong>Salvar como</strong> também existe no iPhone para armazenar localmente ou no servidor partituras criadas ou alteradas no editor móvel.</li><li>A biblioteca local permite criar e renomear pastas. Somente pastas vazias podem ser excluídas.</li><li>Um salvamento correto mostra uma mensagem breve; erros permanecem visíveis.</li></ul>
        <h3>Publicar no servidor</h3><p>Salvar no servidor publica a partitura e mantém uma cópia local. BaraBeat Studio guarda nela um token de publicação, que comprova a permissão para atualizar ou retirar essa publicação.</p><ul><li>Salvar novamente o mesmo arquivo publicado atualiza a publicação.</li><li>Um nome novo cria outra publicação.</li><li><strong>Remover publicação</strong> exclui a versão do servidor e mantém a local.</li><li>Sem token, o arquivo pode ser lido, mas não gerenciado como publicação própria. Use o navegador ou app que o publicou.</li></ul><p>A coluna de status diferencia arquivos locais, publicações e versões alteradas localmente, e informa mudanças posteriores no servidor.</p>
        <h3>SVG, PDF e impressão</h3><p>Em <strong>Arquivo → Exportar</strong>, digite um nome e escolha:</p><ul><li><strong>SVG</strong>, arquivo vetorial escalável para edição ou exibição de alta qualidade.</li><li><strong>PDF</strong>, adequado para compartilhar e imprimir com layout estável.</li></ul><p>Para imprimir, abra o PDF exportado e use o comando do navegador ou sistema. BaraBeat Studio não tem diálogo próprio de impressão.</p>
        <div class="hint"><strong>Observação:</strong> A partitura também armazena configurações e cenários de prática, seleções de Pattern, linha do tempo do Arranjo, volumes, Swing, Feel e outros metadados.</div>
      </section>
