<?php
if (!defined('BARABEAT_MANUAL_RENDER')) { http_response_code(404); exit; }
?>      <section id="editor">
        <h2>4. Editar a partitura</h2><p>A partitura é a base das outras funções. Pattern são trechos identificados por seletores de instrumento e função.</p>
        <h3>Tipos de partitura</h3><table><thead><tr><th>Tipo</th><th>Grade</th><th>Uso típico</th></tr></thead><tbody><tr><td>Binária</td><td>Quatro subdivisões por pulso</td><td>Muitos ritmos regulares de Djembe e Dunun</td></tr><tr><td>Ternária</td><td>Três subdivisões por pulso</td><td>Ritmos baseados em tercinas</td></tr><tr><td>9/8</td><td>Três grupos de três</td><td>Ritmos especiais em 9/8, como Koreduga</td></tr></tbody></table>
        <h3>Partituras com várias páginas</h3><p>Cada página mostra dez linhas. Use <strong>Adicionar página</strong> quando precisar. A legenda fica na última página, com números como <code>1/2</code> e <code>2/2</code> no canto inferior direito.</p>
        <h3>Paleta</h3><p>Contém notas, seletores e sinais de controle. No desktop, permanece visível durante a rolagem e pode ser movida. No editor móvel em paisagem, é uma barra horizontal rolável na parte inferior.</p>
        <h3>Definir instrumento e função</h3><p>O seletor de instrumento define a parte instrumental, por exemplo Djembe, Kenkeni, Sangban, Dununba ou Ballet Dununs. O seletor de função indica Call, Intro, Pattern de acompanhamento, Solo, Échauffement ou Outro. Para <strong>Pattern de acompanhamento</strong> e <strong>Solo</strong>, você pode digitar um nome próprio, como <em>Pattern de acompanhamento 2</em> ou <em>Solo 1</em>, que reaparece ao editar.</p><p><strong>Ballet Dununs</strong> designa no BaraBeat Studio a parte conjunta ou o conjunto tocado por Kenkeni, Sangban e Dununba.</p>
        <h3>Nome do ritmo</h3><p>Fica no alto e pode ser editado diretamente. Ao abrir, o último título carregado é restaurado se o navegador ainda tiver essa informação.</p>
        <h3>Reprodução imediata pela partitura</h3><p>Ao lado do nome ficam BPM e Play. As caixas antes dos Pattern definem o que será reproduzido. Elas ficam ativas assim que um compasso é reconhecido por instrumento, nome ou notas, sem salvar e recarregar. No iPhone, o cabeçalho permanece visível durante a rolagem.</p><ul><li>Um Pattern selecionado repete até Stop.</li><li>Pattern de instrumentos diferentes tocam em paralelo.</li><li>Pattern do mesmo instrumento tocam em sequência.</li><li>Um Acompanhamento continua enquanto um Solo adicional toca em paralelo. Seu Out é ignorado para manter o loop contínuo.</li><li>As notas que soam são destacadas brevemente.</li></ul>
        <h3>Mover um Pattern completo</h3><p>As setas no início movem para cima ou para baixo um Pattern inteiro com notas, seletores e marcas. Funciona no desktop e no editor móvel em paisagem.</p>
      </section>
