<?php
if (!defined('BARABEAT_MANUAL_RENDER')) { http_response_code(404); exit; }
?>      <section id="practice">
        <h2>8. Modo de prática</h2><p>O modo de prática permite praticar Pattern individuais de forma repetida. Ele lê a partitura e constrói um loop com a seleção de Pattern.</p>
        <h3>Seleção de Pattern</h3><p>Pode abrir ou fechar e contém:</p><ul><li><strong>Configurações</strong> de início do Acompanhamento, repetições, temporizador, Swing, Feel, Mute e latência.</li><li><strong>Selecionar acompanhamento</strong> para Pattern reproduzidos em paralelo como base.</li><li><strong>Selecionar partes de prática</strong> para Calls, Intros, Solos, Échauffements, pausas e Pattern de acompanhamento a praticar.</li></ul><p>No desktop, <strong>Configurações</strong> começa recolhido e as duas seleções expandidas. No smartphone, os três começam recolhidos para priorizar o player e as notas.</p>
        <h3>Cenários de prática</h3><p>Uma partitura pode salvar vários cenários com configurações, Acompanhamentos, partes, ordem, repetições, temporizador, progressão, volumes e outros valores.</p><p>Escolha o cenário ao lado de <strong>Modo de prática</strong> ou na seleção. A lista é alfabética. <strong>Configurações atuais</strong> indica que nenhum cenário salvo está ativo.</p><p><strong>Novo</strong> cria um cenário, <strong>Salvar</strong> atualiza o escolhido e <strong>Excluir</strong> o remove. A cópia local da partitura também é atualizada.</p>
        <h3>Início do acompanhamento</h3><p>Pode começar imediatamente, depois de Call, Intro ou Call + Intro. Os que já são partes não são duplicados. Pausas e ShortBars permitem que os Acompanhamentos recomecem juntos.</p>
        <h3>Parar acompanhamento durante Call/Intro</h3><p>Para ritmos em que o Acompanhamento para durante Call ou Intro e depois continua.</p>
        <h3>Partes e ordem</h3><p>Selecione várias partes e ordene arrastando. A repetição do bloco define quantas vezes seu Pattern toca. Opcionalmente, o Acompanhamento pode tocar sozinho entre partes.</p>
        <h3>Repetições e temporizador</h3><ul><li><strong>Repetições</strong> define quantas vezes toca o loop.</li><li><strong>Temporizador</strong> pode definir minutos.</li><li>Ao terminar o tempo, o loop atual chega ao fim.</li></ul>
        <h3>Progressão de tempo</h3><p>Defina tempo inicial, alvo, a cada quantas repetições aumenta e quanto. Primeiro a progressão é concluída; depois continuam as repetições normais ou o temporizador.</p><p>O player mostra os BPM atuais.</p>
        <h3>Padrão de mãos e pausa H2H = mudo</h3><p>O Padrão de mãos é escolhido por Pattern de Djembe, como <strong>Auto</strong>, <strong>H2H</strong> ou outros. Com <strong>Pausa H2H = mudo</strong>, notas vazias viram golpes Mute suaves, com volume por instrumento.</p>
        <h3>Volume</h3><p>Tocar no nome do instrumento abre seu volume. Outro painel equilibra Bass, Tone, Slap ou Mute.</p>
        <h3>Pulso de Shekere</h3><p>Shekere conta quatro pulsos antes de começar. <strong>Pulso de Shekere</strong> também pode acentuar cada pulso durante a reprodução. Existe em prática e Arranjo e tem volume próprio.</p>
      </section>
