<?php
if (!defined('BARABEAT_MANUAL_RENDER')) { http_response_code(404); exit; }
?>      <section id="mobile">
        <h2>11. Uso em smartphones</h2><p>BaraBeat Studio permite abrir, visualizar, reproduzir, praticar e editar partituras. As funções mudam com a orientação. Um Arranjo existente pode ser reproduzido, mas ainda não editado no celular.</p>
        <h3>Controles móveis</h3><p>O menu mostra apenas o necessário. <strong>Arquivo</strong> contém Abrir, Salvar, Salvar como, manual e Sair. <strong>Voltar à partitura</strong> retorna do manual. Na prática aparecem <strong>Seleção de Pattern</strong> e <strong>Latência</strong>. Se houver Arranjo, <strong>Reproduzir arranjo</strong> abre o player em um painel.</p>
        <h3>Retrato e paisagem</h3><ul><li><strong>Retrato:</strong> leitura compacta, um compasso por linha, reprodução imediata, prática e reprodução de Arranjos.</li><li><strong>Paisagem:</strong> editor com grade ampliada, menu Partitura e paleta horizontal.</li></ul>
        <h3>Visualização móvel</h3><p>Partituras com várias páginas são mostradas página a página, não reduzidas a uma tela. Cada compasso ocupa uma linha. Pattern com vários compassos são agrupados e o nome aparece só no começo.</p><p>Nas notas em movimento, instrumento e Pattern ficam na mesma linha. A linha vermelha atravessa apenas as linhas de notas.</p>
        <h3>Editar em paisagem</h3><ol><li>Gire o iPhone.</li><li>Escolha uma nota ou sinal na paleta inferior e toque na posição.</li><li>Mova elementos diretamente e solte para encaixar.</li><li>Desenhe um retângulo com seleção e mova, duplique ou exclua o conjunto.</li><li><strong>Inserir instrumento e função</strong> adiciona os seletores a um compasso vazio; depois podem ser alterados, movidos ou excluídos.</li><li>As setas da linha de seletores movem todo o Pattern.</li><li>Edite o nome no alto; a ferramenta de texto adiciona comentários.</li><li>Salve com <strong>Arquivo → Salvar</strong> ou <strong>Salvar como</strong>.</li></ol>
        <div class="hint"><strong>Toque:</strong> A paleta permanece embaixo e rola horizontalmente. Um toque duplo em uma repetição abre seu ajuste. O teclado iOS pode aparecer; ao fechar, a escala permanece.</div>
        <h3>Reprodução imediata no iPhone</h3><p>As caixas, BPM e Play estão disponíveis. Instrumentos diferentes tocam em paralelo e Pattern do mesmo instrumento em sequência. As notas são destacadas e o cabeçalho permanece visível.</p>
        <h3>Uso offline</h3><ol><li>Abra BaraBeat Studio completamente uma vez por <strong>HTTPS</strong>.</li><li>Aguarde <strong>Pronto para uso offline</strong>.</li><li>Carregue antes do servidor as partituras necessárias.</li><li>Opcionalmente use <strong>Compartilhar &gt; Adicionar à Tela de Início</strong>.</li></ol><p>Offline, partituras locais podem ser abertas, vistas, editadas, tocadas e salvas localmente. Lista e operações do servidor exigem Internet.</p>
        <h3>Segundo plano e tela bloqueada</h3><p>Em aparelhos compatíveis, Media Session e uma sessão de reprodução permitem continuar com a tela bloqueada. Título, logo e controles aparecem conforme iOS, navegador e saída.</p>
        <div class="warning"><strong>Salve antes de excluir:</strong> Safari e o app da Tela de Início podem ter armazenamentos separados. Excluir o app pode apagar partituras, cenários, configurações e dados offline. Adicionar novamente não restaura. Salve antes no servidor; cenários incluídos vão com a partitura. Arquivos do servidor não são apagados.</div>
        <h3>Desempenho e memória</h3><p>iOS Safari é sensível a áudio e muitos elementos DOM. O player limita a pré-renderização de repetições e notas e evita manter samples duplicados.</p>
      </section>
