<?php
if (!defined('BARABEAT_MANUAL_RENDER')) { http_response_code(404); exit; }
?>      <section id="interface">
        <h2>2. Interfaz</h2><p>La aplicación consta de la partitura, una paleta móvil, el menú principal y vistas opcionales para el modo de práctica y el Arreglo.</p>
        <h3>Menú principal</h3><table><thead><tr><th>Menú</th><th>Finalidad</th></tr></thead><tbody><tr><td><strong>Archivo</strong></td><td>Abrir y guardar partituras, administrarlas localmente o en el servidor, exportarlas y elegir el idioma. En smartphones también permite abrir el manual.</td></tr><tr><td><strong>Partitura</strong></td><td>Crear una partitura binaria, ternaria o en 9/8 y añadir o eliminar páginas.</td></tr><tr><td><strong>Insertar</strong></td><td>Insertar elementos o plantillas adicionales.</td></tr><tr><td><strong>Herramientas</strong></td><td>En escritorio, abrir el modo de práctica, el Arreglo, el manual y la selección de plantillas.</td></tr></tbody></table>
        <h3>Idioma</h3><p>En <strong>Archivo → Idioma</strong> puedes elegir <strong>Deutsch</strong>, <strong>English</strong>, <strong>Français</strong>, <strong>Español</strong> o <strong>Português</strong>. BaraBeat Studio recuerda la selección. Solo cambian los controles y mensajes visibles; los datos musicales, textos libres y partituras guardadas no se traducen ni modifican.</p>
        <h3>Inicio de sesión</h3><p>Si la protección está activa, BaraBeat Studio solicita una contraseña. La sesión permanece en ese navegador o app de la pantalla de inicio hasta elegir <strong>Archivo → Cerrar sesión</strong> o borrar los datos. Cierra la sesión en dispositivos compartidos.</p>
        <h3>Administración: acceso temporal</h3><p>Después de iniciar sesión, <strong>Archivo → Abrir acceso durante 5 min</strong> suspende temporalmente la contraseña para todos, incluidos navegadores automatizados, API y herramientas de prueba sin sesión ni cookie. Una confirmación evita aperturas accidentales. El botón muestra el tiempo restante y puede cerrar antes; la protección vuelve a los cinco minutos.</p><p>Durante ese periodo, las respuestas llevan <code>noindex</code> y <code>no-store</code>. Las herramientas automatizadas pueden entrar, pero los buscadores no deben indexar ni almacenar la aplicación.</p>
        <h3>Plantillas</h3><p><strong>Herramientas → Plantilla</strong> permite cambiar entre estilos como <strong>Claro</strong>, <strong>Lúdico</strong> y <strong>Tierra</strong>. Solo cambia la apariencia, no los datos musicales.</p>
      </section>
