<?php
if (!defined('BARABEAT_MANUAL_RENDER')) { http_response_code(404); exit; }
?>      <section id="files">
        <h2>3. Abrir y guardar archivos</h2><p>Las partituras se guardan como archivos <code>.bbs</code>. También se pueden abrir partituras antiguas <code>.txt</code>.</p>
        <h3>Abrir</h3><ul><li><strong>Local</strong> muestra las partituras guardadas en este navegador o app de la pantalla de inicio. Se pueden organizar en carpetas y subcarpetas.</li><li><strong>Servidor</strong> muestra las partituras de <code>Noten/</code>. La lista se actualiza al abrir el diálogo.</li><li>Al cargar del servidor, BaraBeat Studio recuerda la fecha y versión. Si después cambia, aparece <strong>El servidor cambió desde entonces</strong>. Una edición propia se indica aparte como <strong>Modificado localmente</strong> con fecha.</li><li>Cuando procede, el aviso ofrece <strong>Cargar versión del servidor</strong>.</li><li>En smartphones, la vista simplificada mantiene accesibles la apertura y eliminación de archivos locales.</li></ul>
        <h3>Guardar</h3><ul><li><strong>Guardar</strong> sobrescribe la partitura abierta.</li><li><strong>Guardar como</strong> crea otro nombre o una copia.</li><li><strong>Guardar como</strong> también está disponible en iPhone para guardar localmente o en el servidor partituras creadas o modificadas allí.</li><li>La biblioteca local permite crear y renombrar carpetas. Solo se elimina una carpeta vacía.</li><li>Un guardado correcto muestra un mensaje breve; los errores permanecen visibles.</li></ul>
        <h3>Publicar en el servidor</h3><p>Guardar en el servidor publica la partitura y mantiene una copia local. BaraBeat Studio guarda en ella un token de publicación que acredita el derecho a actualizar o retirar la publicación.</p><ul><li>Volver a guardar el mismo archivo publicado actualiza la publicación.</li><li>Un nombre nuevo crea otra publicación.</li><li><strong>Eliminar publicación</strong> quita la versión del servidor y conserva la local.</li><li>Sin token, el archivo se puede leer, pero no administrar como publicación propia. Usa el navegador o app que lo publicó.</li></ul><p>La columna de estado distingue archivos locales, publicaciones y versiones modificadas localmente, y avisa de cambios posteriores en el servidor.</p>
        <h3>SVG, PDF e impresión</h3><p>En <strong>Archivo → Exportar</strong>, escribe un nombre y elige:</p><ul><li><strong>SVG</strong>, archivo vectorial escalable para edición o representación de calidad.</li><li><strong>PDF</strong>, adecuado para compartir e imprimir con una composición estable.</li></ul><p>Para imprimir, abre el PDF exportado y usa la orden del navegador o sistema. BaraBeat Studio no tiene un diálogo de impresión propio.</p>
        <div class="hint"><strong>Nota:</strong> La partitura también guarda ajustes y escenarios de práctica, selecciones de Pattern, la línea de tiempo del Arreglo, volúmenes, Swing, Feel y otros metadatos.</div>
      </section>
