<?php
if (!defined('BARABEAT_MANUAL_RENDER')) { http_response_code(404); exit; }
?>      <section id="editor">
        <h2>4. Editar la partitura</h2><p>La partitura es la base de todas las funciones. Los Pattern son pasajes identificados mediante selectores de instrumento y función.</p>
        <h3>Tipos de partitura</h3><table><thead><tr><th>Tipo</th><th>Cuadrícula</th><th>Uso habitual</th></tr></thead><tbody><tr><td>Binaria</td><td>Cuatro subdivisiones por pulso</td><td>Muchos ritmos regulares de Djembe y Dunun</td></tr><tr><td>Ternaria</td><td>Tres subdivisiones por pulso</td><td>Ritmos en tresillos</td></tr><tr><td>9/8</td><td>Tres grupos de tres</td><td>Ritmos especiales en 9/8 como Koreduga</td></tr></tbody></table>
        <h3>Partituras de varias páginas</h3><p>Cada página muestra diez líneas. Usa <strong>Añadir página</strong> para ampliar. La leyenda aparece en la última página y abajo a la derecha se muestran números como <code>1/2</code> y <code>2/2</code>.</p>
        <h3>Paleta</h3><p>Contiene notas, selectores y signos de control. En escritorio permanece visible durante el desplazamiento y se puede mover. En el editor móvil horizontal es una barra desplazable en la parte inferior.</p>
        <h3>Definir instrumento y función</h3><p>El selector de instrumento define la parte instrumental, por ejemplo Djembe, Kenkeni, Sangban, Dununba o Ballet Dununs. El selector de función indica Call, Intro, Pattern de acompañamiento, Solo, Échauffement u Outro. Para <strong>Pattern de acompañamiento</strong> y <strong>Solo</strong> puedes escribir un nombre propio, como <em>Pattern de acompañamiento 2</em> o <em>Solo 1</em>, que reaparece al editarlo.</p><p><strong>Ballet Dununs</strong> designa en BaraBeat Studio la parte conjunta o el conjunto interpretado por Kenkeni, Sangban y Dununba.</p>
        <h3>Nombre del ritmo</h3><p>Se encuentra arriba y se edita directamente. Al iniciar, se recupera el último título cargado si el navegador conserva esa información.</p>
        <h3>Reproducción inmediata desde la partitura</h3><p>Junto al nombre aparecen BPM y Play. Las casillas delante de los Pattern indican qué se reproduce. Se activan en cuanto un compás se reconoce mediante instrumento, nombre o notas, sin guardar y recargar. En iPhone, la cabecera permanece visible al desplazarse.</p><ul><li>Un Pattern seleccionado se repite hasta Stop.</li><li>Pattern de instrumentos distintos se reproducen en paralelo.</li><li>Pattern del mismo instrumento se reproducen uno tras otro.</li><li>Un Acompañamiento continúa mientras un Solo adicional suena en paralelo. Su Out se ignora para mantener el bucle.</li><li>Las notas que suenan se resaltan brevemente.</li></ul>
        <h3>Mover un Pattern completo</h3><p>Las flechas al inicio permiten mover arriba o abajo un Pattern completo con sus notas, selectores y marcas. Funciona en escritorio y en el editor móvil horizontal.</p>
      </section>
