<?php
if (!defined('BARABEAT_MANUAL_RENDER')) { http_response_code(404); exit; }
?>      <section id="practice">
        <h2>8. Modo de práctica</h2><p>El modo de práctica permite practicar Pattern individuales de forma repetida. Lee la partitura y construye un bucle con la selección de Pattern.</p>
        <h3>Selección de Pattern</h3><p>Puede abrirse o cerrarse y contiene:</p><ul><li><strong>Ajustes</strong> para inicio del Acompañamiento, repeticiones, temporizador, Swing, Feel, Mute y latencia.</li><li><strong>Seleccionar acompañamiento</strong> para Pattern que se reproducen en paralelo como base.</li><li><strong>Seleccionar partes de práctica</strong> para Calls, Intros, Solos, Échauffements, pausas y Pattern de acompañamiento que se quieran practicar.</li></ul><p>En escritorio, <strong>Ajustes</strong> comienza plegado y las dos selecciones desplegadas. En smartphone los tres comienzan plegados para priorizar el reproductor y las notas.</p>
        <h3>Escenarios de práctica</h3><p>Una partitura puede guardar varios escenarios con ajustes, Acompañamientos, partes, orden, repeticiones, temporizador, progresión, volúmenes y otros valores.</p><p>El escenario se elige junto a <strong>Modo de práctica</strong> o en la selección. La lista es alfabética. <strong>Ajustes actuales</strong> significa que no hay escenario guardado activo.</p><p><strong>Nuevo</strong> crea uno, <strong>Guardar</strong> actualiza el elegido y <strong>Eliminar</strong> lo borra. También se actualiza la partitura local.</p>
        <h3>Inicio del acompañamiento</h3><p>Puede comenzar inmediatamente, después de Call, Intro o Call + Intro. Los ya elegidos como parte no se duplican. Pausas y ShortBars permiten que los Acompañamientos vuelvan a empezar juntos.</p>
        <h3>Detener acompañamiento durante Call/Intro</h3><p>Para ritmos en los que el Acompañamiento se detiene durante Call o Intro y continúa después.</p>
        <h3>Partes y orden</h3><p>Selecciona varias partes y ordénalas arrastrando. La repetición del bloque fija cuántas veces suena ese Pattern. Opcionalmente, el Acompañamiento puede sonar solo entre partes.</p>
        <h3>Repeticiones y temporizador</h3><ul><li><strong>Repeticiones</strong> define cuántas veces suena el bucle.</li><li><strong>Temporizador</strong> puede fijar minutos.</li><li>El bucle actual termina completo cuando vence el temporizador.</li></ul>
        <h3>Progresión de tempo</h3><p>Define tempo inicial, objetivo, cada cuántas repeticiones sube y cuánto. Primero se completa la progresión; después continúan las repeticiones normales o el temporizador.</p><p>El reproductor muestra los BPM actuales.</p>
        <h3>Patrón de manos y silencio H2H = mute</h3><p>El Patrón de manos se elige por Pattern de Djembe, por ejemplo <strong>Auto</strong>, <strong>H2H</strong> u otros. Con <strong>Silencio H2H = mute</strong>, las notas vacías se oyen como golpes Mute suaves, con volumen por instrumento.</p>
        <h3>Volumen</h3><p>Pulsar el nombre del instrumento abre su volumen. Otro panel permite equilibrar Bass, Tone, Slap o Mute.</p>
        <h3>Pulso de Shekere</h3><p>Shekere cuenta cuatro pulsos antes de empezar. <strong>Pulso de Shekere</strong> también puede acentuar cada pulso durante la reproducción. Está disponible en práctica y Arreglo y tiene volumen propio.</p>
      </section>
