<?php
if (!defined('BARABEAT_MANUAL_RENDER')) { http_response_code(404); exit; }
?>      <section id="mobile">
        <h2>11. Uso en smartphones</h2><p>BaraBeat Studio permite abrir, ver, reproducir, practicar y editar partituras. Las funciones cambian con la orientación. Un Arreglo existente puede reproducirse, pero aún no editarse en móvil.</p>
        <h3>Controles móviles</h3><p>El menú muestra solo lo relevante. <strong>Archivo</strong> contiene Abrir, Guardar, Guardar como, manual y Cerrar sesión. <strong>Volver a la partitura</strong> regresa desde el manual. En práctica aparecen <strong>Selección de Pattern</strong> y <strong>Latencia</strong>. Si existe Arreglo, <strong>Reproducir arreglo</strong> abre el reproductor en un panel.</p>
        <h3>Vertical y horizontal</h3><ul><li><strong>Vertical:</strong> lectura compacta, un compás por fila, reproducción inmediata, práctica y reproducción de Arreglos.</li><li><strong>Horizontal:</strong> editor con cuadrícula ampliada, menú Partitura y paleta horizontal.</li></ul>
        <h3>Vista móvil</h3><p>Las partituras multipágina se muestran página a página, no reducidas a una sola pantalla. Cada compás ocupa una fila. Los Pattern de varios compases se agrupan y el nombre aparece solo al comienzo.</p><p>En las notas en movimiento, instrumento y Pattern comparten una línea. La línea roja cruza solo las filas de notas.</p>
        <h3>Editar en horizontal</h3><ol><li>Gira el iPhone.</li><li>Elige una nota o signo en la paleta inferior y pulsa la posición.</li><li>Mueve directamente los elementos y suéltalos para encajar.</li><li>Dibuja un marco con selección y mueve, duplica o elimina el conjunto.</li><li><strong>Insertar instrumento y función</strong> añade ambos selectores a un compás vacío; después pueden cambiarse, moverse o eliminarse.</li><li>Las flechas de la fila de selectores mueven todo el Pattern.</li><li>Edita arriba el nombre; la herramienta de texto añade comentarios.</li><li>Guarda con <strong>Archivo → Guardar</strong> o <strong>Guardar como</strong>.</li></ol>
        <div class="hint"><strong>Uso táctil:</strong> La paleta permanece abajo y se desplaza horizontalmente. Un doble toque en una repetición abre su ajuste. El teclado iOS puede aparecer; al cerrarlo se conserva la escala.</div>
        <h3>Reproducción inmediata en iPhone</h3><p>Las casillas, BPM y Play están disponibles. Instrumentos distintos suenan en paralelo y Pattern del mismo instrumento en serie. Las notas se resaltan y la cabecera permanece visible.</p>
        <h3>Uso sin conexión</h3><ol><li>Abre BaraBeat Studio una vez mediante <strong>HTTPS</strong>.</li><li>Espera a <strong>Disponible sin conexión</strong>.</li><li>Carga antes del servidor las partituras necesarias.</li><li>Opcionalmente usa <strong>Compartir &gt; Añadir a pantalla de inicio</strong>.</li></ol><p>Sin conexión se pueden abrir, ver, editar, reproducir y guardar localmente. La lista y operaciones del servidor requieren Internet.</p>
        <h3>Segundo plano y pantalla bloqueada</h3><p>En dispositivos compatibles, Media Session y una sesión de reproducción permiten continuar con la pantalla bloqueada. Se muestran título, logo y controles según iOS, navegador y salida.</p>
        <div class="warning"><strong>Guarda antes de eliminar:</strong> Safari y la app de inicio pueden tener almacenamientos separados. Eliminar la app puede borrar partituras, escenarios, ajustes y datos offline. Volver a añadirla no los restaura. Guarda antes lo importante en el servidor; los escenarios incluidos viajan con la partitura. Los archivos del servidor no se borran.</div>
        <h3>Rendimiento y memoria</h3><p>iOS Safari es sensible al audio y a muchos elementos DOM. El reproductor limita el prerenderizado de repeticiones y notas, y evita mantener samples duplicados.</p>
      </section>
