<?php
if (!defined('BARABEAT_MANUAL_RENDER')) { http_response_code(404); exit; }
?>      <section id="practice">
        <h2>8. Mode entraînement</h2><p>Le mode entraînement sert à répéter des Patterns. Il lit les Patterns de la partition et construit une boucle d’entraînement.</p>
        <h3>Sélection de Pattern</h3><p>Elle s’ouvre ou se ferme et comprend :</p><ul><li><strong>Réglages</strong> pour le début de l’Accompagnement, les répétitions, le minuteur, Swing, Feel, Mute et la latence.</li><li><strong>Sélectionner l’Accompagnement</strong> pour les Patterns joués en parallèle comme rythme de base.</li><li><strong>Sélectionner les parties d’entraînement</strong> pour Calls, Intros, Solos, Échauffements, pauses et Patterns d’accompagnement à travailler.</li></ul><p>Sur ordinateur, <strong>Réglages</strong> est d’abord replié, les deux sélections sont dépliées. Sur smartphone, les trois restent d’abord repliées pour privilégier le lecteur et les notes défilantes.</p>
        <h3>Scénarios d’entraînement</h3><p>Plusieurs scénarios peuvent être enregistrés avec une partition. Ils contiennent les réglages, les accompagnements, les parties, l’ordre, les répétitions, le minuteur, la progression du tempo, les volumes et d’autres valeurs.</p><p>Le scénario actif se choisit près de <strong>Mode entraînement</strong> ou dans la sélection. La liste est alphabétique. <strong>Réglages actuels</strong> signifie qu’aucun scénario enregistré n’est actif.</p><p><strong>Nouveau</strong> crée un scénario, <strong>Enregistrer</strong> actualise celui sélectionné et <strong>Supprimer</strong> le retire. Ces actions actualisent aussi la copie locale de la partition.</p>
        <h3>Début de l’Accompagnement</h3><p>Il peut commencer immédiatement, après Call, après Intro ou après Call et Intro. Un Call ou une Intro déjà choisi comme partie n’est pas ajouté deux fois. Pauses et ShortBars sont pris en compte pour que les Accompagnements repartent ensemble.</p>
        <h3>Arrêter l’Accompagnement pendant Call/Intro</h3><p>Cette option concerne les rythmes dont l’Accompagnement s’interrompt pendant un Call ou une Intro avant de reprendre.</p>
        <h3>Parties et ordre</h3><p>Plusieurs parties peuvent être sélectionnées et glissées dans l’ordre voulu. Le nombre de répétitions d’un bloc détermine combien de fois son Pattern est joué dans la séquence. L’accompagnement peut aussi jouer seul entre les parties.</p>
        <h3>Répétitions et minuteur</h3><ul><li><strong>Répétitions</strong> fixe le nombre de boucles.</li><li><strong>Minuteur</strong> peut définir une durée en minutes.</li><li>Avec le minuteur, la boucle en cours se termine au lieu de s’arrêter au milieu d’un Pattern.</li></ul>
        <h3>Progression du tempo</h3><p>Définissez un tempo initial, un tempo cible, le nombre de répétitions entre les augmentations et leur valeur. La progression se joue d’abord entièrement ; les répétitions normales ou le minuteur suivent.</p><p>Le lecteur affiche les BPM actuels pendant la progression.</p>
        <h3>Alternance des mains et silence H2H = sourdine</h3><p>Le mode d’alternance des mains peut être choisi pour chaque Pattern de Djembe, par exemple <strong>Auto</strong>, <strong>H2H</strong> ou d’autres modes. Avec <strong>Silence H2H = sourdine</strong>, les notes vides deviennent des frappes Mute discrètes dont le volume peut dépendre de l’instrument.</p>
        <h3>Volume</h3><p>Un clic sur le nom d’instrument des notes défilantes ouvre son volume. Un autre panneau règle Bass, Tone, Slap ou Mute les uns par rapport aux autres.</p>
        <h3>Pulsation Shekere</h3><p>Shekere compte quatre pulsations avant le départ. <strong>Pulsation Shekere</strong> peut aussi accentuer chaque battement pendant la lecture. La fonction existe dans l’entraînement et l’Arrangement ; Shekere a son propre volume.</p>
      </section>
