<?php
if (!defined('BARABEAT_MANUAL_RENDER')) { http_response_code(404); exit; }
?>      <section id="mobile">
        <h2>11. Utilisation sur smartphone</h2><p>Sur smartphone, BaraBeat Studio ouvre, affiche, lit immédiatement, entraîne et modifie des partitions. L’affichage et l’édition changent automatiquement avec l’orientation. Une timeline d’Arrangement existante peut être lue mais pas encore modifiée sur mobile.</p>
        <h3>Commandes mobiles</h3><p>La barre de menu ne montre que les commandes utiles. <strong>Fichier</strong> contient Ouvrir, Enregistrer, Enregistrer sous, le mode d’emploi et Déconnexion. Le bouton permanent <strong>Retour à la partition</strong> quitte le mode d’emploi. En entraînement, <strong>Sélection de Pattern</strong> et <strong>Latence</strong> sont aussi disponibles. Si la partition contient un Arrangement, <strong>Lire l’Arrangement</strong> ouvre son lecteur dans un panneau.</p>
        <h3>Portrait et paysage</h3><ul><li><strong>Portrait :</strong> lecture compacte, une mesure par ligne, lecture immédiate, entraînement et lecture d’Arrangements.</li><li><strong>Paysage :</strong> éditeur mobile avec grille agrandie, menu Partition et palette horizontale.</li></ul>
        <h3>Partition mobile</h3><p>Les partitions de plusieurs pages s’affichent page par page, sans réduire toute la pile à la hauteur de l’écran. Chaque mesure a sa ligne. Les Patterns de plusieurs mesures sont regroupés ; instrument et nom n’apparaissent qu’au début.</p><p>Dans les notes défilantes, instrument et Pattern tiennent sur une ligne. La ligne rouge ne traverse que les lignes de notes pour laisser les noms lisibles.</p>
        <h3>Modifier en paysage</h3><ol><li>Tournez l’iPhone en paysage.</li><li>Choisissez une note ou un signe dans la palette du bas, puis touchez la position de grille.</li><li>Déplacez directement les éléments existants ; ils rejoignent la grille au relâchement.</li><li>Tracez un cadre avec l’outil de sélection, puis déplacez, dupliquez ou supprimez l’ensemble.</li><li><strong>Insérer instrument et fonction</strong> ajoute les deux sélecteurs à une mesure libre. Ils peuvent ensuite être modifiés, déplacés ou supprimés.</li><li>Les flèches de la ligne des sélecteurs déplacent tout le Pattern.</li><li>Modifiez le nom du rythme en haut ; l’outil texte insère des commentaires.</li><li>Enregistrez avec <strong>Fichier → Enregistrer</strong> ou <strong>Enregistrer sous</strong>.</li></ol>
        <div class="hint"><strong>Gestes :</strong> La palette reste en bas et défile horizontalement. Un double toucher sur une reprise ouvre son réglage. Le clavier iOS peut apparaître ; sa fermeture ne change pas l’échelle de la partition.</div>
        <h3>Lecture immédiate sur iPhone</h3><p>Les cases de Pattern, BPM et Play sont disponibles. Plusieurs instruments jouent en parallèle, les Patterns d’un même instrument à la suite. Les notes qui sonnent sont surlignées. L’en-tête reste visible pour pouvoir arrêter à tout moment.</p>
        <h3>Utilisation hors ligne</h3><ol><li>Ouvrez une fois complètement BaraBeat Studio par une connexion <strong>HTTPS</strong>.</li><li>Attendez <strong>Prêt hors ligne</strong> : interface, lecteur et sons sont préparés.</li><li>Chargez auparavant du serveur les partitions nécessaires.</li><li>Ajoutez éventuellement l’app dans Safari avec <strong>Partager &gt; Sur l’écran d’accueil</strong>.</li></ol><p>Hors connexion, les partitions locales peuvent être ouvertes, affichées, modifiées, lues et enregistrées localement. La liste serveur et les opérations serveur exigent Internet.</p>
        <h3>Arrière-plan et écran verrouillé</h3><p>Sur les appareils compatibles, BaraBeat Studio utilise Media Session et une session audio de lecture. Le son peut continuer écran verrouillé. L’écran affiche titre, logo et commandes Play, Pause et Stop selon iOS, le navigateur et la sortie audio.</p>
        <div class="warning"><strong>Sauvegardez avant suppression :</strong> Safari et l’app de l’écran d’accueil peuvent utiliser des stockages séparés. Supprimer l’app peut effacer partitions locales, scénarios, réglages et données hors ligne. La rajouter ne les restaure pas. Publiez auparavant les partitions importantes sur le serveur ; les scénarios intégrés sont inclus. Les fichiers serveur restent intacts.</div>
        <h3>Performances et mémoire</h3><p>iOS Safari est sensible à l’audio et aux nombreux éléments DOM. Le lecteur limite donc le prérendu des répétitions et des notes défilantes et évite de conserver plusieurs fois les samples.</p>
      </section>
