<?php
if (!defined('BARABEAT_MANUAL_RENDER')) { http_response_code(404); exit; }
?>      <section id="workflows">
        <h2>12. Procédures courantes</h2>
        <h3>Noter un nouveau Pattern</h3><ol><li>Créez une partition binaire, ternaire ou 9/8 et nommez le rythme.</li><li>Placez le sélecteur d’instrument, par exemple <em>Djembe 1</em>.</li><li>Placez le sélecteur de fonction, par exemple <em>Pattern d’accompagnement</em>, <em>Call</em> ou <em>Solo 1</em>.</li><li>Glissez les notes de la palette sur les lignes.</li><li>Ajoutez au besoin <strong>In</strong>, <strong>Out</strong>, <strong>Reprise</strong>, <strong>ShortBar</strong> ou triolet/quartolet.</li><li>Enregistrez.</li></ol>
        <h3>Enregistrer et rouvrir</h3><ol><li><strong>Fichier → Enregistrer</strong> actualise la copie locale ; <strong>Enregistrer sous</strong> crée une version.</li><li>Dans <strong>Fichier → Ouvrir</strong>, choisissez <strong>Local</strong>.</li><li>Ouvrez le dossier, sélectionnez et chargez la partition.</li><li>Pour une version serveur, choisissez <strong>Serveur</strong> ; le chargement crée une copie locale.</li></ol>
        <h3>Exporter SVG ou PDF</h3><ol><li>Ouvrez <strong>Fichier → Exporter</strong>.</li><li>Choisissez nom et <strong>SVG</strong> ou <strong>PDF</strong>.</li><li>Lancez, puis ouvrez le PDF pour imprimer.</li></ol>
        <h3>Modifier sur iPhone</h3><ol><li>Ouvrez la partition et tournez l’iPhone.</li><li>Dans une nouvelle mesure, touchez l’outil des sélecteurs puis <strong>Insérer instrument et fonction ici</strong>.</li><li>Choisissez instrument et type de Pattern.</li><li>Choisissez une note et touchez sa position.</li><li>Déplacez-la ou sélectionnez plusieurs éléments.</li><li>Utilisez <strong>Enregistrer</strong> ou <strong>Enregistrer sous</strong>.</li></ol>
        <h3>Vérifier immédiatement un Pattern</h3><ol><li>Cochez le Pattern.</li><li>Ajoutez-en d’autres si besoin.</li><li>Réglez les BPM.</li><li>Appuyez sur Play ; la sélection boucle et les notes sonores sont surlignées.</li><li>Appuyez de nouveau pour arrêter.</li></ol>
        <h3>Travailler un Pattern</h3><ol><li>Ouvrez le mode entraînement.</li><li>Ouvrez la sélection.</li><li>Choisissez un Accompagnement.</li><li>Choisissez et ordonnez les parties.</li><li>Réglez répétitions ou minuteur.</li><li>Enregistrez éventuellement un scénario.</li><li>Appuyez sur Play.</li></ol>
        <h3>Construire un Arrangement</h3><ol><li>Ouvrez l’Arrangement.</li><li>Glissez les Patterns de la Bibliothèque dans la timeline.</li><li>Placez-les dans la même section pour les jouer en parallèle.</li><li>Réglez les répétitions.</li><li>Placez les Solos dans leurs cellules.</li><li>Contrôlez BPM, Swing, Feel et volumes.</li><li>Lisez ou exportez en WAV.</li></ol>
      </section>
